# Generated by Django 5.2.1 on 2025-05-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milky_way', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
