# Generated by Django 5.2.1 on 2025-05-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milky_way', '0003_star_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='star',
            old_name='user_id',
            new_name='user',
        ),
    ]
